name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        
      - name: setup jdk 17 (for gradle)
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: make gradlew executable
        run: chmod +x ./gradlew
        
      - name: build with gradle (using java 17)
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./gradlew build
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pocketfps-build
          path: build/libs/
