name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        
      - name: setup jdk 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: make gradlew executable
        run: chmod +x ./gradlew
        
      - name: build with gradle
        run: ./gradlew build -Dorg.gradle.java.home=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.xx
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pocketfps-build
          path: build/libs/
